### ISSUE TITLE
Translation files missing

### ISSUE THREAD

**Issue by eson57** [a-dekker/displaytime#3]
Hi,

I made a clean install of v0.1.7, and the language files are missing. Don't know if you forgot to add them to package?

**Comment by a-dekker** [comment]
Both the .qm files are in place, Dutch and Swedish work, also after a reinstall.
Or you mean the source.ts files? They are in the github repo.

**Comment by eson57** [comment]
Something must have gone wrong with my install, because no language files was installed. I did another reinstall and now it's okay. Sorry, to bother you with this.
